### PR TITLE
fix(sync.js): trim dead branches on set

### PR DESCRIPTION
**Pull request by mattcreager**
Related: #52

### CODE REVIEW

**Comment by colinmacdonald** [comment]
LGTM

**Comment by ianlivingstone** [comment]
Where are the tests for this @mattcreager @colinmacdonald ?

**Comment by colinmacdonald** [comment]
@ianlivingstone This PR is a hotfix, tests will be done for the next release. https://github.com/goinstant/goangular/issues/52#issuecomment-33840975

**Comment by ianlivingstone** [comment]
Even hot fixes require tests

**Pull request merged**
